### ISSUE TITLE
Enhancement: Line dividers on sub menu should have a consistent width

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#73]
The width for sub menu line dividers are inconsistent.

1. Go to Homepage, Products or Catalogues
i.  Hover on Products >  Machine Tool Accessories 
        The line dividers did not occupy the entire width of the containers
ii. Hover on Catalogues > Thank You
          The line dividers for Thank You sub menu did not occupy the entire width of the container

![header - 09](https://cloud.githubusercontent.com/assets/12888048/8664451/fb9c0a2a-2a09-11e5-9d10-9bdb48dda3f2.jpg)
![header - 10](https://cloud.githubusercontent.com/assets/12888048/8664452/fc94d466-2a09-11e5-8736-edeb37e0dbbb.jpg)

2.  Go to Homepage or Products page
i.  Hover on Catalogues
         The line dividers for Catalogues sub menu occupied the entire width of the container

![header - 13](https://cloud.githubusercontent.com/assets/12888048/8664456/08737ce2-2a0a-11e5-9344-fdafeb209ec0.jpg)

3.  Go to Catalogues page
i.  Hover on Catalogues
         The line dividers for Catalogues sub menu did not occupy the entire width of the container

![header - 12](https://cloud.githubusercontent.com/assets/12888048/8664461/1d796fa2-2a0a-11e5-9dd4-14901baa5f08.jpg)

**Comment by rexcebudigital** [comment]
Hi Roma,

About this,

Go to Homepage, Products or Catalogues i. Hover on Products > Machine Tool Accessories The line dividers did not occupy the entire width of the containers ii. Hover on Catalogues > Thank You The line dividers for Thank You sub menu did not occupy the entire width of the container


Our team decided to leave this as it is because as we can see that the parent li content is 2 lines and the sub is not. We cannot align the parent li and the first li of the submenu.

Thanks.
